### ISSUE TITLE
API accepts statuses for docker artifacts

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#1102]
The `statuses` field is only meant for Debian artifacts, but the API currently accepts that field for docker artifacts.

Example:
```yaml
artifacts:
  - name: spkr/mddemo-titus
    type: docker
    tagVersionStrategy: branch-job-commit-by-job
    reference: mddemo-titus
    statuses:
      - RELEASE
```
