### ISSUE TITLE
Deb status export: do something better

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#1167]
Right now we can't determine deb status. We should be able to based on the name of the artifact. Reach out to the rocket team to see if they have something we can use?

It's pretty bad to not export all the status info.

**Comment by emjburns** [comment]
Also, we need to actually figure out how to do the base os (`bionic-classic` etc)

**Comment by jonsie** [comment]
I exported artifacts today, and I had two artifacts - one for each region:

```
- name: fiat
  type: deb
  reference: fiat
  vmOptions:
    baseLabel: RELEASE
    baseOs: bionic
    regions:
    - us-east-1
    storeType: EBS
- name: fiat
  type: deb
  reference: fiat
  vmOptions:
    baseLabel: RELEASE
    baseOs: bionic
    regions:
    - us-west-2
    storeType: EBS
```

This should be consolidated to:

```
- name: fiat
  type: deb
  reference: fiat
  vmOptions:
    baseLabel: RELEASE
    baseOs: bionic
    regions:
    - us-east-1
    - us-west-2
    storeType: EBS
```
