### ISSUE TITLE
Event history modal does not display application events

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#1176]
The event history modal is currently not displaying application-level events that affect the resource history, namely `ApplicationActuationPaused` and `ApplicationActuationResumed`, as in the following example:
![image](https://user-images.githubusercontent.com/1323478/81987757-293ff080-95ef-11ea-95e2-9eeba7d8b3c9.png)

The matching events returned from the API were as follows (notice the application events in between the `ResourceValid` events):
```yaml
- type: "ResourceValid"
  kind: "titus/cluster@v1"
  id: "titus:cluster:titustestvpc:mddemotitus-prestaging"
  application: "mddemotitus"
  timestamp: "2020-05-14T20:57:37.525Z"
  scope: "resource"
  uid: "titus:cluster:titustestvpc:mddemotitus-prestaging"
- type: "ApplicationActuationResumed"
  application: "mddemotitus"
  triggeredBy: "lpollo@netflix.com"
  timestamp: "2020-05-14T20:47:33.338Z"
  scope: "application"
  uid: "mddemotitus"
- type: "ApplicationActuationPaused"
  application: "mddemotitus"
  timestamp: "2020-05-14T20:47:22.215Z"
  triggeredBy: "lpollo@netflix.com"
  scope: "application"
  uid: "mddemotitus"
- type: "ResourceValid"
  kind: "titus/cluster@v1"
  id: "titus:cluster:titustestvpc:mddemotitus-prestaging"
  application: "mddemotitus"
  timestamp: "2020-05-12T05:02:07.351Z"
  scope: "resource"
  uid: "titus:cluster:titustestvpc:mddemotitus-prestaging"
- type: "ResourceCheckUnresolvable"
  kind: "titus/cluster@v1"
  id: "titus:cluster:titustestvpc:mddemotitus-prestaging"
  application: "mddemotitus"
  timestamp: "2020-05-12T05:01:06.820Z"
  message: "No digest found for docker image spkr/mddemo-titus:master-h16.fa3d725\
    \ in any registry"
  scope: "resource"
  uid: "titus:cluster:titustestvpc:mddemotitus-prestaging"
```
