### ISSUE TITLE
allowed-time constraint broken (ui + keel)

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#1263]
The allowed-times constraint seems to not be evaluating correctly

```yaml
---
windows:
- days: mon-fri
  hours: 7-16
type: allowed-times
```

This did not "pass" on Tuesday at 11 am. This also did not show in the UI at all. cc @erikmunson
