### ISSUE TITLE
keel incorrectly validates delivery configs with invalid references

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1271]
A delivery config that has an invalid artifacts reference (i.e., refers to an artifact that is defined in the delivery config) isn't valid, but it passes keel validation.

Here's an example of a delivery config with an invalid reference (`this-ref-does-not-exist-in-this-config`) that passes validation:

```yaml
name: broken-example
application: foo
serviceAccount: keel@spinnaker
artifacts:
  - name: org/thing
    type: docker
    reference: org/thing
environments:
  - name: testing
    resources:
      - kind: titus/cluster@v1
        spec:
          moniker:
            app: foo
          locations:
            account: testing
            regions:
              - name: us-east-1
          container:
            reference: this-ref-does-not-exist-in-this-config
```
