### ISSUE TITLE
"stagger" functionality in deployWith does not wait for initial region completion

### ISSUE THREAD

**Issue by robzienert** [spinnaker/keel#1487]
Given a `ec2/cluster@v1` kind, the `deployWith` spec has a `stagger` section that, according to my understanding, should rollout a single region and then wait to deploy other regions until the first one is _complete_. Our observations are that all regions are deployed at the same time:

```yaml
          deployWith:
            delayBeforeScaleDown: PT1H
            resizePreviousToZero: true
            rollbackOnFailure: false
            strategy: red-black
            stagger:
              - region: us-west-2
                pauseTime: PT30S
```

Our observed behavior is that the pause time is applied to the start of the first deployment, so other regions are deploying 30 seconds after the first one starts.

![Screen Shot 2020-09-09 at 4 20 38 PM](https://user-images.githubusercontent.com/108741/92664318-7b9ccf80-f2b8-11ea-83f5-17fdba79bb02.png)
