### ISSUE TITLE
Delivery config validation accepts invalid artifact references in clusters

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#1534]
The following delivery config should not be accepted by keel, but is (note the artifact has a reference, but the `container.reference` field in the cluster spec has the artifact name, not the reference:
```yaml
name: myapp
application: myapp
serviceAccount: myapp@netflix.com
artifacts:
  - name: myapp
     reference: myref
     type: docker
     tagVersionStrategy: semver-job-commit-by-semver
environments:
  - name: testing
    resources:
      - kind: titus/cluster@v1
        spec:
          container:
            reference: myapp
          locations:
            account: titustestvpc
            regions:
              - name: us-east-1
            vpc: vpc0
          moniker:
            app: myapp
```
