### ISSUE TITLE
False delta detected in cluster tags

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#416]
```yaml
  delta:
    /tags:
      state: "CHANGED"
      updated: "{}"
      previous: "{}"
```
