### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#442]
Resources should have some way to notify 
- when the resource changes (start/end of actuation?)
- maybe when there's an error
- maybe when there's a diff detected

We could default to emailing the service account (at netflix, this is usually the team's DL).
We could provide notification config for each resource.
We could provide notification config as an overall "resource" or "config", tie it to an app, and have some options on this to control which events we're notifying for as well as who is being notified.

**Comment by emjburns** [comment]
The rocket team has started with this config in the `rocket.yml` file:

```yml
notifications:
  stash:
    enabled: true|false
  slack:
  - channel: my-team-channel
    rocketBranch: master
    conditions:
    - failure
  - channel: my-other-channel
    rocketBranch: pull/\d+
    conditions:
    - failure
    - success
    - aborted
  email:
  - to:
    - myteam-critical@netflix.com
    rocketBranch: master
    conditions:
    - failure
  - to:
    - myteam-noncritical@netflix.com
    - devnull@netflix.com
    rocketBranch: pull/\d+
    conditions:
    - failure
    - success
    - aborted
```

**Comment by emjburns** [comment]
Preliminary idea: an environment can have notifications (same for every resource that supports them). Config is a list of notifications at the environment level.

```yaml
notifications:
- type: slack
  address: #my-slack-channel
  frequency: VERBOSE / NORMAL / QUIET
- type: email
  address: my-email@blah.com
  frequency: QUIET
```
where:
VERBOSE: starting, complete, failed
NORMAL: complete, failed
QUIET: failed
