### ISSUE TITLE
Suggestion for more concise resource definitions

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#490]
I understand we're trying to make the `resources` field in the YAML extensible, and that it may contain heterogeneous resource definitions (e.g. images, clusters, etc), so using the full Kubernetes-based format, including the "header" with the `apiVersion`, `kind` and `metadata` is a way to achieve that, but it also makes for very verbose files.

I was thinking that we might be able to retain that extensibility while reducing the verbosity of the files by introducing well-defined resource types as child fields of `resources`. This is similar to how [Kubernetes probes are defined](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#probe-v1-core), for instance. Given that new code will necessarily need to be added to Keel to process new types of resources, adding the well-known resource types would not seem to take away from the extensibility of the format.

This format would also have the added benefit or making supported resource types first-class citizens of the format, which I think is a good thing since users will not arbitrarily define new resource types (I think, right?).

For example, instead of:
```yaml
    resources:
      - apiVersion: "bakery.spinnaker.netflix.com/v1"
        kind: "image"
        metadata:
          serviceAccount: "delivery-engineering@netflix.com"
        spec:
          artifactName: keeldemo
          baseLabel: RELEASE
          baseOs: "xenial"
          regions:
            - us-west-2
            - us-east-1
          storeType: EBS
          application: keeldemo
      - apiVersion: "ec2.spinnaker.netflix.com/v1"
        kind: "cluster"
        metadata:
          serviceAccount: "delivery-engineering@netflix.com"
        spec:
          imageProvider:
            deliveryArtifact:
              name: keeldemo
              type: DEB
          moniker:
            app: "keeldemo"
            stack: "test"
          locations:
            accountName: "test"
            regions:
              - region: "us-west-2"
                subnet: "internal (vpc0)"
                availabilityZones:
                  - "us-west-2a"
                  - "us-west-2b"
                  - "us-west-2c"
              - region: "us-east-1"
                subnet: "internal (vpc0)"
                availabilityZones:
                  - "us-east-1c"
                  - "us-east-1d"
                  - "us-east-1e"
          launchConfiguration:
            instanceType: "m5.large"
            ebsOptimized: true
            iamRole: "keeldemoInstanceProfile"
            keyPair: "nf-test-keypair-a"
          capacity:
            min: 1
            max: 1
            desired: 1
          dependencies:
            loadBalancerNames:
              - "keeldemo-test-clb"
            securityGroupNames:
              - "keeldemo"
              - "nf-datacenter"
              - "nf-infrastructure"
            targetGroups:
              - "keeldemo-test"
          overrides: {}
```

You could have:
```yaml
    resources:
      images:
      - serviceAccount: "delivery-engineering@netflix.com"
        artifactName: keeldemo
        baseLabel: RELEASE
        baseOs: "xenial"
        regions:
          - us-west-2
          - us-east-1
        storeType: EBS
        application: keeldemo
      clusters:
      - serviceAccount: "delivery-engineering@netflix.com"
        imageProvider:
          deliveryArtifact:
            name: keeldemo
            type: DEB
        moniker:
          app: "keeldemo"
          stack: "test"
        locations:
          accountName: "test"
          regions:
            - region: "us-west-2"
              subnet: "internal (vpc0)"
              availabilityZones:
                - "us-west-2a"
                - "us-west-2b"
                - "us-west-2c"
            - region: "us-east-1"
              subnet: "internal (vpc0)"
              availabilityZones:
                - "us-east-1c"
                - "us-east-1d"
                - "us-east-1e"
        launchConfiguration:
          instanceType: "m5.large"
          ebsOptimized: true
          iamRole: "keeldemoInstanceProfile"
          keyPair: "nf-test-keypair-a"
        capacity:
          min: 1
          max: 1
          desired: 1
        dependencies:
          loadBalancerNames:
            - "keeldemo-test-clb"
          securityGroupNames:
            - "keeldemo"
            - "nf-datacenter"
            - "nf-infrastructure"
          targetGroups:
            - "keeldemo-test"
        overrides: {}
```
In the proposal above, I wasn't sure how important it was to have `serviceAccount` in the `metadata`. I assumed it was OK to just move that together with the fields in the `spec`.

If you have a large enough file, and/or if we end up generating these files for the majority of cases, then perhaps this doesn't matter, but I thought I'd offer up the suggestion. Feel free to disregard if it doesn't make sense. 😄
