### ISSUE TITLE
Non-screaming names for artifact types in YAML definitions

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#557]
When defining artifacts on resources, we use the values that keel defines on its own enum of artifact types which are in `SCREAMING_CAMEL_CASE`, e.g.

```yaml
imageProvider:
    deliveryArtifact:
      name: "grpc-lab-emunson-server"
      type: "DEB" or "DOCKER_IMAGE"
```

This looks a bit out of place in the YAML definitions themselves, and ideally I'd love to see us move to something less screamy, e.g.

```yaml
imageProvider:
    deliveryArtifact:
      name: "grpc-lab-emunson-server"
      type: "deb" or "docker"
```

This should probably be done as a backwards-compatible change where we just coerce differently-cased values to the enum value, so we can migrate existing definitions without hassle.
