### ISSUE TITLE
Use more of the currently implemented defaults on cluster exports

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#581]
The cluster export endpoint does a lovely job defaulting many of the fields we currently have good values for, but there are some fields that remain in exported specs even though we support defaults and most people use them:

- `ebsOptimized`, `iamRole`, `keyPair`, and `instanceMonitoring` inside `launchConfiguration`
- The `vpc` and `subnet` fields (I believe these are currently not defaulted via export because the spec defaulting mechanism is different than other fields)
- The entire `health` block — e.g. if I export a cluster I always get:
```
    cooldown: "PT10S"
    warmup: "PT10M"
    healthCheckType: "EC2"
    terminationPolicies:
    - "Default"
```
