### ISSUE TITLE
Ability to stagger cluster deploys by region

### ISSUE THREAD

**Issue by asher** [spinnaker/keel#600]
Clusters are multi-region capable resources that are evaluated as an individual entity. This also means you cannot define distinct `ec2:cluster:test:keel-demo` resources for different regions, so I don't think environment constraints will provide a good solution here.

Ideas for what cluster region staggering could look like:

```
apiVersion: ec2.spinnaker.netflix.com/v1
kind: cluster
metadata:
  serviceAccount: my-email@spinnaker.io
spec:
  moniker:
    app: keeldemo
    stack: examples
    detail: ec2v1
  imageProvider:
    deliveryArtifact:
      name: keeldemo
      type: DEB
  locations:
    account: test
    vpc: vpc0
    subnet: internal (vpc0)
    regions:
      - name: us-west-2
      - name: us-east-1
      - name: eu-west-1
  regionStaggerInterval: 1h
```

In this example, the regions list denotes ordering for a staggered roll out, which may look like:

 - 00:00 us-west-2 deploy starts
 - 00:30 us-west-2 deploy finishes
 - 01:30: us-east-1 deploy starts
 - 01:55: us-east-1 deploy finishes
 - 02:55: eu-west-1 deploy starts 

Another approach would be to extend the allowed-times constraint so that it can be applied on a region-scoped basis within a cluster.
