### ISSUE TITLE
Default options for red-black strategy don't get omitted during export

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#625]
When you export a cluster with all the default red/black options, the fields still make it into the spec. e.g.:

```yaml
deployWith:
  delayBeforeDisable: PT0S
  delayBeforeScaleDown: PT0S
  maxServerGroups: 2
  resizePreviousToZero: false
  rollbackOnFailure: true
  strategy: red-black
```

**Comment by gal-yardeni** [comment]
@luispollo Are you taking care of omitting the `deployWith` section as a part of #627 ?

**Comment by luispollo** [comment]
@gal-yardeni No, #627 was to solve a very specific problem with the existing export/resolution behavior. Deployments strategies are new in the spec which is why they were not included in the original PR to omit defaults. I've assigned this issue to myself to address that in a separate PR.

**Comment by luispollo** [comment]
Dupe of #640?

**Comment by erikmunson** [comment]
If we close export defaults issues that are scoped to a specific default value in favor of a catch-all "default all the exported things" issue, then we should still take the examples from each issue and put them in the catch-all issue so we know what we're currently seeing not defaulted properly.

**Comment by luispollo** [comment]
@erikmunson It turns out that the reason that's showing up in the export is that it is a mandatory field in the spec, and it has a default of `RedBlack()` (i.e. red-black with all default options). In other words, we're not looking at the actual resources in the cloud to figure out what the strategy is on export, we're always setting it to the default. I think someone mentioned we may have that info in tags somewhere, but I'm not familiar.

Regardless, as I said, `deployWith` is currently a mandatory field, so I'm inclined to close this bug unless we want to change that behavior (and then I'll need some help with the tags).

BTW, I keep having second thoughts on whether omitting fields with defaults on export is a good idea. I understand your rationale for making the exported specs less verbose and overwhelming, but the fact is that they will likely just go from machine (export) to machine (import to keel) without any human editing, so why do we care? Under the covers, this is making the export code much more complex and bug-prone. I've been working on a refactoring to simplify what we can, but there's only so far we can go because some defaults are dynamic, so we can't automate the entire process as I'd like. Given this, my feeling that we loose more than we gain from omitting defaults. Just food for thought...

**Comment by luispollo** [comment]
@erikmunson Case in point: as part of #695, I've made changes to omit the defaults in the Titus cluster export. Here's an example of what a portion of the spec like looked like before the change:
```yaml
spec:
  moniker:
    app: "serverlablpollo"
  locations:
    account: "titustestvpc"
    vpc: "vpc0"
    regions:
    - name: "us-east-1"
    - name: "us-west-2"
    - name: "eu-west-1"
  overrides:
    us-west-2:
      capacity:
        min: 2
        max: 2
        desired: 2
  container:
    organization: "emburns"
    image: "spin-titus-demo"
    digest: "sha256:3b919225c332aa46aeba3eda7c9a6be6b3bd87f09c3bebed1863a3c8dd4e28ca"
  capacity:
    min: 1
    max: 1
    desired: 1
```
...and after:
```yaml
spec:
  moniker:
    app: "serverlablpollo"
  locations:
    account: "titustestvpc"
    vpc: "vpc0"
    regions:
    - name: "us-east-1"
    - name: "us-west-2"
    - name: "eu-west-1"
  overrides:
    us-west-2:
      capacity:
        min: 2
        max: 2
        desired: 2
  container:
    organization: "emburns"
    image: "spin-titus-demo"
    digest: "sha256:3b919225c332aa46aeba3eda7c9a6be6b3bd87f09c3bebed1863a3c8dd4e28ca"
```
In the latter example, we omit the `capacity` field from the top-level properties because it has all-default values, but the spec is harder to read, IMHO -- what is the `capacity` field in the region override changing?

Thoughts?
