### ISSUE TITLE
/managed/resources/export exports incorrect deployWith strategy

### ISSUE THREAD

**Issue by coryb** [spinnaker/keel#753]
My cluster is currently managed with:
```
     deployWith:
       strategy: highlander
```
but if I export the same cluster it returns with the default redblack:
```
      deployWith:
        delayBeforeDisable: PT0S
        delayBeforeScaleDown: PT0S
        maxServerGroups: 2
        resizePreviousToZero: false
        rollbackOnFailure: true
        strategy: red-black
```

The export should honor the currently managed deployWith strategy.

Ideally we would be able to inspect current deployment pipelines for clusters to infer the correct strategy when exporting a non-managed cluster to be managed, but for now we need it to be consistent with the currently managed strategy.
