### ISSUE TITLE
/managed/resources/export no longer exports default capacity

### ISSUE THREAD

**Issue by coryb** [spinnaker/keel#754]
My current cluster has:
```
     capacity:
       desired: 1
       max: 1
       min: 1
```

But when I export now the entire `capacity` section is dropped.  I think we probably want to export capacity constraints no mater what, that seems like a property that will usually want to be tuned and should always remain visible in config files.

Similarly for titus clusters the `resources` config is dropped if those are default, this is a config I currently use that is no longer exported:
```
     resources:
       cpu: 1
       disk: 10000
       gpu: 0
       memory: 512
       networkMbps: 128
```
For similar reasons, I think we likely want to export titus resource constraints, even if they are default values.
