### ISSUE TITLE
Export should put only differences in overrides, not things that are the same between regions 

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#762]
Also, you're allowed to leave keypair blank (and you probably should). We shouldn't export that.

For example:

Actual:
```yaml
- apiVersion: ec2.spinnaker.netflix.com/v1
    kind: cluster
    metadata: {}
    spec:
      capacity:
        desired: 2
        max: 2
        min: 2
...
      launchConfiguration:
        ebsOptimized: true
        instanceType: r4.xlarge # why are you here instance type?
        keyPair: nf-keypair-111-us-east-1 # this shouldn't be shown even though technically it's different...
      overrides:
        eu-west-1:
          launchConfiguration:
            ebsOptimized: true
            instanceType: r4.xlarge
            keyPair: nf-keypair-111-eu-west-1
        us-west-2:
          capacity:
            desired: 3
            max: 3
            min: 3
          launchConfiguration:
            ebsOptimized: true
            instanceType: r4.xlarge
            keyPair: nf-keypair-111-us-west-2
```

expected:
```yaml
  - apiVersion: ec2.spinnaker.netflix.com/v1
    kind: cluster
    metadata: {}
    spec:
      capacity:
        desired: 2
        max: 2
        min: 2
...
      launchConfiguration:
        ebsOptimized: true
        instanceType: r4.xlarge
      overrides:
        us-west-2:
          capacity:
            desired: 3
            max: 3
            min: 3
```
